version: 2.1

orbs:
  aws-cdk-orb: homebound-team/aws-cdk-orb@10.0.1
  node: circleci/node@5.0.1

only-run-on-branches: &only-run-on-branches
  branches:
    ignore:
      - main

only-run-on-main: &only-run-on-main
  branches:
    only:
      - main

workflows:
  version: 2
  workflow:
    jobs:
      - test:
          context:
            - npm-readonly
            - dockerhub
      - aws-cdk-orb/build-branch:
          name: build-dev
          context:
            - aws-creds-dev
            - npm-readonly
            - dockerhub
          filters:
            <<: *only-run-on-branches
          stage: dev
          executor: aws-cdk-orb/machine
      - aws-cdk-orb/deploy:
          name: deploy-dev
          stage: dev
          context:
            - aws-creds-dev
            - npm-readonly
            - dockerhub
          filters:
            <<: *only-run-on-main
          executor: aws-cdk-orb/machine
     
jobs:
  test:
    docker:
      - image: cimg/node:16.14.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: 'echo "npmAuthToken: $NPM_TOKEN" >> ${HOME}/.yarnrc.yml'
      - node/install-packages:
          pkg-manager: yarn-berry
      - run: yarn test --runInBand
